<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SQLProvider.Fable.Rust\SQLProvider.Fable.Rust.fsproj" />
    <ProjectReference Include="..\SQLProvider.Fable.SmokeTests\SQLProvider.Fable.SmokeTests.fsproj" />
  </ItemGroup>

</Project>
