// Generated by SQLProvider.Fable. Do not edit.
//
// Regenerate rather than adjust: the column names here have to match the
// database exactly, and a hand edit is a silent mismatch waiting to happen.
module SQLProvider.Fable.SmokeTests.GeneratedSchema

open SQLProvider.Fable

/// Customer
module Customer =

    let table = "Customer"

    let CustomerId = Col.int64 table "CustomerId"
    let Name = Col.text table "Name"
    let Country = Col.text table "Country"
    let Balance = Col.float table "Balance"
    let Joined = Col.date table "Joined"
    let Discount = Col.decimal table "Discount"
    let Active = Col.bool table "Active"
    let Photo = Col.blob table "Photo"

    /// One row, as a record.
    type Row =
        { CustomerId: int64
          Name: string
          Country: string option
          Balance: float
          Joined: System.DateTime option
          Discount: decimal option
          Active: bool
          Photo: byte[] option }

    let ofRow (r: SqlRow) : Row =
        { CustomerId = Row.int64 r "CustomerId"
          Name = Row.text r "Name"
          Country = Row.textOpt r "Country"
          Balance = Row.float r "Balance"
          Joined = Row.dateTimeOpt r "Joined"
          Discount = Row.decimalOpt r "Discount"
          Active = Row.bool r "Active"
          Photo = Row.blobOpt r "Photo" }

    /// Every column aliased Table_Column, for selecting this table out of a
    /// join without column-name collisions:
    /// `selectAs (Array.append A.qualified B.qualified)`. Read the results
    /// back with `ofQualifiedRow`.
    let qualified =
        [| "Customer_CustomerId", CustomerId.E
           "Customer_Name", Name.E
           "Customer_Country", Country.E
           "Customer_Balance", Balance.E
           "Customer_Joined", Joined.E
           "Customer_Discount", Discount.E
           "Customer_Active", Active.E
           "Customer_Photo", Photo.E |]

    /// `ofRow` over the `qualified` aliases.
    let ofQualifiedRow (r: SqlRow) : Row =
        { CustomerId = Row.int64 r "Customer_CustomerId"
          Name = Row.text r "Customer_Name"
          Country = Row.textOpt r "Customer_Country"
          Balance = Row.float r "Customer_Balance"
          Joined = Row.dateTimeOpt r "Customer_Joined"
          Discount = Row.decimalOpt r "Customer_Discount"
          Active = Row.bool r "Customer_Active"
          Photo = Row.blobOpt r "Customer_Photo" }

/// Orders
module Orders =

    let table = "Orders"

    let OrderId = Col.int64 table "OrderId"
    let CustomerId = Col.int64 table "CustomerId"
    let Freight = Col.decimal table "Freight"

    /// One row, as a record.
    [<Struct>]
    type Row =
        { OrderId: int64
          CustomerId: int64
          Freight: decimal }

    let ofRow (r: SqlRow) : Row =
        { OrderId = Row.int64 r "OrderId"
          CustomerId = Row.int64 r "CustomerId"
          Freight = Row.decimal r "Freight" }

    /// Every column aliased Table_Column, for selecting this table out of a
    /// join without column-name collisions:
    /// `selectAs (Array.append A.qualified B.qualified)`. Read the results
    /// back with `ofQualifiedRow`.
    let qualified =
        [| "Orders_OrderId", OrderId.E
           "Orders_CustomerId", CustomerId.E
           "Orders_Freight", Freight.E |]

    /// `ofRow` over the `qualified` aliases.
    let ofQualifiedRow (r: SqlRow) : Row =
        { OrderId = Row.int64 r "Orders_OrderId"
          CustomerId = Row.int64 r "Orders_CustomerId"
          Freight = Row.decimal r "Orders_Freight" }

    /// Join conditions from this table's foreign keys.
    module Relations =

        /// Orders.CustomerId = Customer.CustomerId
        let toCustomer = Expr.eq (ColumnRef(table, "CustomerId")) (ColumnRef("Customer", "CustomerId"))

